### Buscar todos los mensajes
POST http://localhost:3000/api/message
Content-Type: application/json

{
  "receiver": "test",
  "sender": "abraham"
}

### Buscar conversaciones
POST http://localhost:3000/api/conversation
Content-Type: application/json

{
  "username": "abraham"
}

### Buscar ultimo mensaje enviado
POST http://localhost:3000/api/message/time
Content-Type: application/json

{
  "receiver": "test",
  "sender": "abraham"
}